
# Install all node modules and build the project. 
# If fails on this stage, revise the packages defined and React.
build-job:
  stage: build
  tags:
    - general
  script:
    - npm run install-project
    - node build_decades.js
  artifacts:
    paths:
      - deployment/

# Run the node testing script checking general server functionality
test-job:
  stage: test
  dependencies:
    - build-job
  tags:
    - general
  script:
    - npm --prefix ./deployment/ install
    - node pipeline_test.js

deploy-to-cloud-job:
  stage: deploy
  dependencies:
    - build-job
  tags:
    - general
  script:
    - echo $DEPLOY_KEY_FILE_PRODUCTION > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud --quiet --project $PROJECT_ID_PRODUCTION app deploy deployment/app.yaml
    - rm /tmp/$CI_PIPELINE_ID.json

  